//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrialContoroler.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndustrialContoroler.Resource.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافة مرفق جديد بنجاح.
        /// </summary>
        public static string AddNewAttachment {
            get {
                return ResourceManager.GetString("AddNewAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أضافة منشأة جديدة بنجاح.
        /// </summary>
        public static string AddNewFacility {
            get {
                return ResourceManager.GetString("AddNewFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية.
        /// </summary>
        public static string AddRequest {
            get {
                return ResourceManager.GetString("AddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافة الطلب بنجاح يرجى احالته للمدير العام.
        /// </summary>
        public static string AddRequestDone {
            get {
                return ResourceManager.GetString("AddRequestDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تسطيع حذف نفسك.
        /// </summary>
        public static string cannotDeleteYourSelf {
            get {
                return ResourceManager.GetString("cannotDeleteYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المرفق بنجاح.
        /// </summary>
        public static string DeleteAttachmentDone {
            get {
                return ResourceManager.GetString("DeleteAttachmentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ اثناء الانشاء.
        /// </summary>
        public static string ErroNOExcepted {
            get {
                return ResourceManager.GetString("ErroNOExcepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ اثناء الحذف.
        /// </summary>
        public static string ErroNOExcepteddelete {
            get {
                return ResourceManager.GetString("ErroNOExcepteddelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ غير متوفع.
        /// </summary>
        public static string ErrorVald {
            get {
                return ResourceManager.GetString("ErrorVald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تمت الموافقة على الطلب سيتم إحالة إستمارة الزيارة الميدانية الى  للسجل الصناعي .
        /// </summary>
        public static string lbacceptDone {
            get {
                return ResourceManager.GetString("lbacceptDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العملية.
        /// </summary>
        public static string lbActionName {
            get {
                return ResourceManager.GetString("lbActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستخدم.
        /// </summary>
        public static string lbActiveUser {
            get {
                return ResourceManager.GetString("lbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة فئات جديدة.
        /// </summary>
        public static string lbAddNewCategory {
            get {
                return ResourceManager.GetString("lbAddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة جديدة.
        /// </summary>
        public static string lbAddNewRole {
            get {
                return ResourceManager.GetString("lbAddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مستخدم جديد.
        /// </summary>
        public static string lbAddNewUsers {
            get {
                return ResourceManager.GetString("lbAddNewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string lbbtnChangePassword {
            get {
                return ResourceManager.GetString("lbbtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lbbtnDelete {
            get {
                return ResourceManager.GetString("lbbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbbtnEdit {
            get {
                return ResourceManager.GetString("lbbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string lbbtnPermissions {
            get {
                return ResourceManager.GetString("lbbtnPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbbtnSave {
            get {
                return ResourceManager.GetString("lbbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف فئة جديدة.
        /// </summary>
        public static string lbbtnSaveNewCategory {
            get {
                return ResourceManager.GetString("lbbtnSaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة جديدة.
        /// </summary>
        public static string lbbtnSaveNewRole {
            get {
                return ResourceManager.GetString("lbbtnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string lbbtnSaveNewUser {
            get {
                return ResourceManager.GetString("lbbtnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        public static string lbbtnSavepermission {
            get {
                return ResourceManager.GetString("lbbtnSavepermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة المرفق بنجاح.
        /// </summary>
        public static string lbbtnSaveRequst {
            get {
                return ResourceManager.GetString("lbbtnSaveRequst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string lbcancelButtonText {
            get {
                return ResourceManager.GetString("lbcancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الفئات.
        /// </summary>
        public static string lbCategories {
            get {
                return ResourceManager.GetString("lbCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كلمة المرور.
        /// </summary>
        public static string lbComparePassword {
            get {
                return ResourceManager.GetString("lbComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الحذف.
        /// </summary>
        public static string lbconfirmButtonText {
            get {
                return ResourceManager.GetString("lbconfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الفئة.
        /// </summary>
        public static string lbDescription {
            get {
                return ResourceManager.GetString("lbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string lbEmailUser {
            get {
                return ResourceManager.GetString("lbEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string lbEvents {
            get {
                return ResourceManager.GetString("lbEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string lbImageUser {
            get {
                return ResourceManager.GetString("lbImageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الفئات.
        /// </summary>
        public static string lbLogCategories {
            get {
                return ResourceManager.GetString("lbLogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string lbManageBook {
            get {
                return ResourceManager.GetString("lbManageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الصلاحيات.
        /// </summary>
        public static string lbManagePermission {
            get {
                return ResourceManager.GetString("lbManagePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف مجموع الفئات.
        /// </summary>
        public static string lbMsgDeletedOkCategory {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الاستمارة بنجاح.
        /// </summary>
        public static string lbMsgDeletedOkfiled {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkfiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المستخدم بنجاح..
        /// </summary>
        public static string lbMsgDeletedOkRegister {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الطلب بنجاح.
        /// </summary>
        public static string lbMsgDeletedOkRequest {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف مجموعة المستخدم..
        /// </summary>
        public static string lbMsgDeletedOkRole {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لهذه الصفحة.
        /// </summary>
        public static string lbMsgDenied {
            get {
                return ResourceManager.GetString("lbMsgDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتستطيع الحفظ لان اسم الفئة موجود.
        /// </summary>
        public static string lbMsgDuplicateNameCategory {
            get {
                return ResourceManager.GetString("lbMsgDuplicateNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم او كلمة المرور غير صحيح.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ الفئة.
        /// </summary>
        public static string lbMsgNotSavedCategory {
            get {
                return ResourceManager.GetString("lbMsgNotSavedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغير كلمة المرور.
        /// </summary>
        public static string lbMsgNotSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ فئة جديدة.
        /// </summary>
        public static string lbMsgSaveCategory {
            get {
                return ResourceManager.GetString("lbMsgSaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير كلمة المرور بنجاح.
        /// </summary>
        public static string lbMsgSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الفئة بنجاح.
        /// </summary>
        public static string lbMsgUpdateCategory {
            get {
                return ResourceManager.GetString("lbMsgUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string lbNameCategory {
            get {
                return ResourceManager.GetString("lbNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string lbNameRole {
            get {
                return ResourceManager.GetString("lbNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string lbNameUser {
            get {
                return ResourceManager.GetString("lbNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحذف.
        /// </summary>
        public static string lbNotDeleteRole {
            get {
                return ResourceManager.GetString("lbNotDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين المراد حذفها اساسية في النظام.
        /// </summary>
        public static string lbNotdeleteRoleMs {
            get {
                return ResourceManager.GetString("lbNotdeleteRoleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string lbNotEditteRole {
            get {
                return ResourceManager.GetString("lbNotEditteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!الأسم الذي تم التعديل الية موجود في النظام مسبقاً.
        /// </summary>
        public static string lbNotEditteRoleMs {
            get {
                return ResourceManager.GetString("lbNotEditteRoleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string lbNotSaved {
            get {
                return ResourceManager.GetString("lbNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة المستخدم.
        /// </summary>
        public static string lbNotSavedMsgRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مجموعة الصلاحيات موجود مسبقاً.
        /// </summary>
        public static string lbNotSavedMsgRolealreadyExists {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRolealreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ المستخدم.
        /// </summary>
        public static string lbNotSavedMsgUser {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة المستخدم.
        /// </summary>
        public static string lbNotSavedMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسناً.
        /// </summary>
        public static string lbOk {
            get {
                return ResourceManager.GetString("lbOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إحالة الأستمارة الى المختص الفني للتعديل عليها.
        /// </summary>
        public static string lbreferenceDone {
            get {
                return ResourceManager.GetString("lbreferenceDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إحالة استمارة الزيارة الميدانية الى مدير عام الرقابة بنجاح.
        /// </summary>
        public static string lbreferenceFieldtoGeneDone {
            get {
                return ResourceManager.GetString("lbreferenceFieldtoGeneDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إحالة الطلب الى المختص الفني بنجاح.
        /// </summary>
        public static string lbreferenceReDone {
            get {
                return ResourceManager.GetString("lbreferenceReDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إحالة الطلب الى مدير عام الرقابة الصناعية بنجاح.
        /// </summary>
        public static string lbreferenceReToAdmminDone {
            get {
                return ResourceManager.GetString("lbreferenceReToAdmminDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الأحالة.
        /// </summary>
        public static string lbrefernce {
            get {
                return ResourceManager.GetString("lbrefernce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string lbRegisters {
            get {
                return ResourceManager.GetString("lbRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoles {
            get {
                return ResourceManager.GetString("lbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoleUser {
            get {
                return ResourceManager.GetString("lbRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مستخدم جديد بنجاح.
        /// </summary>
        public static string lbSaveMsgUser {
            get {
                return ResourceManager.GetString("lbSaveMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مجموعة المستخدم.
        /// </summary>
        public static string lbSelectUserRole {
            get {
                return ResourceManager.GetString("lbSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الأرسال.
        /// </summary>
        public static string lbsendMessage {
            get {
                return ResourceManager.GetString("lbsendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أرسال أشعارك الى المستحدم الذي حددته.
        /// </summary>
        public static string lbsendMessageDon {
            get {
                return ResourceManager.GetString("lbsendMessageDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن تتمكن من التراجع عن هذا !!.
        /// </summary>
        public static string lbTextMsgDelete {
            get {
                return ResourceManager.GetString("lbTextMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود من قبل .
        /// </summary>
        public static string lbthenameisDuplicate {
            get {
                return ResourceManager.GetString("lbthenameisDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف!.
        /// </summary>
        public static string lbTitleDeletedOk {
            get {
                return ResourceManager.GetString("lbTitleDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbTitleEdit {
            get {
                return ResourceManager.GetString("lbTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مجموعة الفئات.
        /// </summary>
        public static string lbTitleEditCategory {
            get {
                return ResourceManager.GetString("lbTitleEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات مستخدم.
        /// </summary>
        public static string lbTitleEditUser {
            get {
                return ResourceManager.GetString("lbTitleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد ؟.
        /// </summary>
        public static string lbTitleMsgDelete {
            get {
                return ResourceManager.GetString("lbTitleMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافه مستخدم بنجاح.
        /// </summary>
        public static string lbtnSaveUser {
            get {
                return ResourceManager.GetString("lbtnSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل المستخدم بنجاح.
        /// </summary>
        public static string lbUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين الحالين.
        /// </summary>
        public static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن قبول ملف غير صورة.
        /// </summary>
        public static string notaccepfileNoImage {
            get {
                return ResourceManager.GetString("notaccepfileNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الرفض.
        /// </summary>
        public static string rejectRequest {
            get {
                return ResourceManager.GetString("rejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لن يتم إحالة إستمارة الزيارة الميدانية الى الادارة العامة للسجل .
        /// </summary>
        public static string rejectRequestDon {
            get {
                return ResourceManager.GetString("rejectRequestDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية.
        /// </summary>
        public static string RequestEdit {
            get {
                return ResourceManager.GetString("RequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الطلب بنجاح.
        /// </summary>
        public static string RequestEditDon {
            get {
                return ResourceManager.GetString("RequestEditDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
